# Generated by Django 5.2.9 on 2025-12-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('CONFIRMED', 'confirmed'), ('DELIVERED', 'delivered')], default='PENDING', max_length=25),
        ),
    ]
